<?php
require_once('../../TCPDF/tcpdf.php');
class MYPDF extends TCPDF {
    public function Header() {
        // Logo
        $image_file = 'logo.png';
        $this->Image($image_file, 10, 10, 30, '', 'PNG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        // Set font
        $this->SetFont('helvetica', 'B', 20);
        $this->Cell(0, 15, 'Payment Receipt', 0, false, 'C', 0, '', 0, false, 'M', 'M');
    }
    // Page footer
    public function Footer() {
        $this->SetY(-15);
        $this->SetFont('helvetica', 'I', 8);
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
    // Page body
    public function createPaymentSlip($payment_id) {
        $db = dbConn();
        $sql = "SELECT * FROM payments WHERE id = $payment_id";
        $result = $db->query($sql);
        $payment = $result->fetch_assoc();
        $this->SetFont('helvetica', '', 12);
        $this->Cell(0, 10, 'Payment ID: '. $payment['id'], 0, false, 'L', 0, '', 0, false, 'T', 'M');
        $this->Cell(0, 10, 'Date: '. date('Y-m-d'), 0, false, 'R', 0, '', 0, false, 'T', 'M');
        $this->Ln(10);
        $this->Cell(0, 10, 'Customer Name: '. $payment['customer_name'], 0, false, 'L', 0, '', 0, false, 'T', 'M');
        $this->Cell(0, 10, 'Amount: $'. number_format($payment['amount'], 2), 0, false, 'R', 0, '', 0, false, 'T', 'M');
        $this->Ln(10);
        $this->Cell(0, 10, 'Payment Method: '. $payment['payment_method'], 0, false, 'L', 0, '', 0, false, 'T', 'M');
        $this->Ln(20);
        $this->Cell(0, 10, 'Thank you for your payment!', 0, false, 'C', 0, '', 0, false, 'T', 'M');
        $this->Output('payment_receipt.pdf', 'D');
        $db->close();
        }
        }
        // create new PDF document
        $pdf = new MYPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
        // set document information
        $pdf->SetCreator(PDF_CREATOR);
        $pdf->SetAuthor('Nicola Asuni');
        $pdf->SetTitle('Payment Receipt');
        // set default header data
        $pdf->SetHeaderData('logo.png', 30, 'Payment Receipt', 'Generated by TCPDF');
        // set header margins
        $pdf->SetHeaderMargin(20);
        // set footer margins
        $pdf->SetFooterMargin(20);
        // set auto page breaks
        $pdf->SetAutoPageBreak(true, 20);
        // set font
        $pdf->SetFont('helvetica', '', 10);
        // add a page
        $pdf->AddPage();
        // create payment slip
        $pdf;
        // get payment ID from URL parameter
        $payment_id = isset($_GET['payment_id'])? dataClean($_GET['payment_id']) : 0;
        if ($payment_id <= 0) {
            exit;
        }
        // create the temporary logo image
        copy('logo.png', 'logo.png');
        // create the payment slip and output as a downloadable PDF document
        $pdf->createPaymentSlip($payment_id);
        // close and output PDF document
        $pdf->Output('payment_receipt.pdf', 'D');
        // delete the temporary files
        unlink('logo.png');
        unlink('payment_receipt.pdf');
        exit;
        // end of file
        $payment_id = 123;
        $pdf->createPaymentSlip($payment_id);
        // close and output PDF document
        $pdf->Output('payment_receipt.pdf', 'D');
        // delete the temporary files
        unlink('logo.png');
        unlink('payment_receipt.pdf');
        exit;
        // end of file
    
    // create a database connection
    function dbConn() {
        $dbHost = 'localhost';
        $dbUser = 'root';
        $dbPass = '';
        $dbName ='superzonic';
        $db = new mysqli($dbHost, $dbUser, $dbPass, $dbName);
        if ($db->connect_error) {
            die('Database connection failed: '. $db->connect_error);
        }
        return $db;
    }
    // sanitize data
    function dataClean($data) {
        $data = trim($data);
        $data = stripslashes($data);
        $data = htmlspecialchars($data);
        return $data;
    }
    // end of file

       



  